config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :tasks
  end
  get '/', to: 'front#index'
  get '/filter', to: 'front#filter'
  root 'front#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :user
  validates :name, presence: true,
                    length: { minimum: 3 }

  #scope :statuses,  -> { order('id DESC') }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  validates :name, presence: true,
                    length: { minimum: 3 }
  validates :status, inclusion: { in: %w(new in_process done),
    message: "%{value} is not a valid status" }

    scope :statuses, -> { Task.select('status').order(status: :asc) }
    scope :count_tasks, -> { Task.joins(:project).group("projects.id").select('projects.name, COUNT(*) as cnt').order("cnt DESC")  }
    scope :count_tasks_name, -> { Task.joins(:project).group("projects.id").select('projects.name, COUNT(*) as cnt').order("projects.name ASC")  }
    scope :tasks_n, -> { Task.where("name LIKE ?",'N%')  }
    scope :projects_a, -> { Task.joins(:project).group("projects.id").select('projects.name, COUNT(tasks.id) as cnt').where("projects.name LIKE ?",'%a%')  }
    scope :tasks_dup, -> { Task.select(:name).group(:name).having("count(*) > 1").order(name: :asc)  }
    scope :tasks_garage, -> { Task.joins(:project).where("projects.name = 'GARAGE'").group("tasks.name, tasks.status").having("COUNT(*)>1").select("tasks.name, tasks.status, COUNT(*)").order("COUNT(*) ASC")  }
    scope :tasks_ten_done, -> { Task.joins(:project).where("tasks.status = 'done'").group("projects.id, projects.name").having("COUNT(*)>10").select("projects.id, projects.name, COUNT(*)").order("projects.id ASC")  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/front_controller.rb
class FrontController < ApplicationController

  before_filter :authenticate_user!
  respond_to :json


  def index
    @projects = Project.where("user_id = ?", current_user)
    @project = Project.new
    @task = Task.new
  end

  def all_projects
      @projects = Project.all
  end

  def filter
    @filter = Task.statuses.uniq if params['f'] == 'statuses'
    @filter = Task.count_tasks if params['f'] == 'count-tasks'
    @filter = Task.count_tasks_name if params['f'] == 'count-tasks-order-name'
    @filter = Task.tasks_n if params['f'] == 'tasks-n'
    @filter = Task.projects_a if params['f'] == 'projects-a'
    @filter = Task.tasks_dup if params['f'] == 'tasks-dup'
    @filter = Task.tasks_garage if params['f'] == 'tasks-garage'
    @filter = Task.tasks_ten_done if params['f'] == 'tasks-ten-done'

    respond_to do |format|
      format.json { render :json=>@filter }
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  respond_to :json

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find params[:id]
    @task = Task.new
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)
    @task = Task.new
    @project.save
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
  end

  private
  def project_params
    params.require(:project).permit(:name).merge(user: current_user)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :json

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.new(task_params)
    @task.save
  end

  def edit
    @task = Task.find params[:id]
  end

  def update
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:id])
    @task.update(task_params)
  end

  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    @task.destroy
  end

  private
    def task_params
      params.require(:task).permit(:name, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/front/index.html.erb
<div class='container'>
<h1 class="text-center">SIMPLE TODO LIST</h1>
<% if user_signed_in? %>
  <div calss='row'>
    <div class='col-md-9'>
      <p>SQL filter for all:</p>
        <%= select_tag(:filter, options_for_select([['none', 'none'],
         ['all iniq statuses', 'statuses'],
         ['count all tasks in each project', 'count-tasks'],
         ['count all tasks in each project order by projects name', 'count-tasks-order-name'],
         ['tasks for all projects having the name beginning with “N” letter', 'tasks-n'],
         ['list of all projects containing the ‘a’ letter in the middle of the name', 'projects-a'],
         ['list of tasks with duplicate names, asc', 'tasks-dup'],
         ['list of tasks GARAGE with mathes', 'tasks-garage'],
         ['list of project names having more than 10 tasks in status ‘done’', 'tasks-ten-done']
        ]), :onchange=>'filter(this)') %>
        <br /><br />
    </div>
    <div class='col-md-3 wellcome-message well'>
      <span>Hello, <%= current_user.email %></span><br>
      <%= link_to 'Sing out', destroy_user_session_path, :method => :delete %>
    </div>
  </div>

  <div class='row'>
    <div id='filter-block' class='col-md-12 well' style='display:none;'></div>
  </div>

    <div id='new_project' class='text-center'>
      <%= link_to new_project_path , remote: true, :class => "btn btn-primary"  do %>
        <span class='glyphicon glyphicon-plus'></span> Add TODO List
      <% end %>
    </div><br>

    <div id='projects'>
      <% @projects.each do |project| %>

      <div id=<%= dom_id project %> class='panel panel-default'>

          <div class='panel-heading'>
            <div class='col-md-6'>
              <span class="glyphicon glyphicon-calendar calendar pull-left"></span>
              <p class='name pull-left'><%= project.name %></p>
            </div>
            <div class='col-md-2 col-md-offset-4'>
              <%= link_to project_path(project), remote: true, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="glyphicon glyphicon-trash trash pull-right"></i>
              <% end %>
              <%= link_to edit_project_path(project), remote: true do %>
                <i class="glyphicon glyphicon-pencil pencil pull-right"></i>
              <% end %>
            </div>
          </div>

          <div class='panel-body' id='new_task_<%= dom_id project %>'>
          <%= form_for([project, @task], remote: true) do |f| %>
            <div class='col-md-8'>
              <span class='glyphicon glyphicon-plus plus'></span><%= f.text_field :name, class: 'form-control', placeholder: 'Enter new task' %>
            </div>
            <div class='col-md-2'>
              <%= f.select :status, options_for_select([['new', 'new'] , ['in_process', 'in_process'] ,['done', 'done']]), class: 'form-control' %>
            </div>
            <div class='col-md-2'>
              <%= f.submit class: 'btn btn-default new_task_select'%>
              <% end %>
            </div>
          </div>

            <table id='tasks_<%= dom_id project %>' class='table table-hover'>
              <% unless project.tasks.empty? %>
              <% project.tasks.each do |task| %>
                <tr id=<%= dom_id task %> class='row <%= task.status %>'>
                  <td><p><%= task.name %></p></td>
                  <td><p><%= task.status %></p></td>
                  <td><%= link_to edit_project_task_path(task.project, task ), remote: true, :class => 'delete_task' do %>
                    <i class="glyphicon glyphicon-pencil pencil"></i>
                    <% end %>
                  </td>
                  <td><%= link_to [task.project, task], remote: true, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="glyphicon glyphicon-trash trash"></i>
                    <% end %>
                  </td>
                </tr>
            <% end %>
            <% end %>
          </table>
        </div>
    <% end %>
  </div>
</div>

<% else %>
    <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>

<div id="myModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header"><button class="close" type="button" data-dismiss="modal">×</button>
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer"><button class="btn btn-default" type="button" data-dismiss="modal">Закрыть</button></div>
    </div>
  </div>
</div>

app/views/front/new.js.erb
$('#project-form').html("<%= j (render 'form') %>");
$('#project-form').slideDown(350);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel='stylesheet' src='bootstrap.min.css' />
    <link rel='stylesheet' src='custom.css' />
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_edit.html.erb
<%= form_for :project, url: project_path(@project), method: :patch, remote: true do |f| %>
  <p>
    <%= f.text_field :name %>  <%= f.submit value: 'Rename project'%>
  </p>
<% end %>

app/views/projects/_new.html.erb
<%= form_for :project, url:  projects_path, remote: true do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/projects/_project.html.erb
<div id=<%= dom_id project %> class='panel panel-default'>

  <div class='panel-heading'>
    <div class='col-md-6'>
      <span class="glyphicon glyphicon-calendar calendar pull-left"></span>
      <p class='name pull-left'><%= project.name %></p>
    </div>
    <div class='col-md-2 col-md-offset-4 actions'>
      <%= link_to project_path(project), remote: true, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="glyphicon glyphicon-trash trash pull-right"></i>
      <% end %>
      <%= link_to edit_project_path(project), remote: true do %>
        <i class="glyphicon glyphicon-pencil pencil pull-right"></i>
      <% end %>
    </div>
  </div>

  <div class='panel-body' id='new_task_<%= dom_id project %>'>
  <%= form_for([project, @task], remote: true) do |f| %>
    <div class='col-md-8'>
      <span class='glyphicon glyphicon-plus plus pull-right'></span><%= f.text_field :name, class: 'form-control', placeholder: 'Enter new task' %>
    </div>
    <div class='col-md-2'>
      <%= f.select :status, options_for_select([['new', 'new'] , ['in_process', 'in_process'] ,['done', 'done']]), class: 'form-control' %>
    </div>
    <div class='col-md-2'>
      <%= f.submit class: 'btn btn-default new_task_select'%>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/create.js.erb
$("<%= escape_javascript(render @project) %>").fadeIn(300).appendTo("#projects");
//$("#new_project").html('<%= link_to new_project_path , remote: true, :class => "btn btn-primary" do %>  <span class="glyphicon glyphicon-plus"></span> Add TODO List <% end %>');
$('#myModal').modal("hide");

app/views/projects/destroy.js.erb
$("#project_<%= @project.id %>").remove();

app/views/projects/edit.js.erb
$("#myModal .modal-title").text("Edit project: <%= @project.name %>");
$("#myModal .modal-body").html("<%= j (render 'edit') %>");
$('#myModal').modal("show");

app/views/projects/new.js.erb
$("#myModal .modal-title").text("Create project");
$("#myModal .modal-body").html("<%= j (render 'new') %>");
$('#myModal').modal("show");

app/views/projects/update.js.erb
$('#myModal').modal("hide");
$("#project_<%= @project.id %> .name").text("<%= @project.name %>");

app/views/tasks/_edit.html.erb
<%= form_for :task, url: project_task_path(@task.project, @task), method: :patch, remote: true do |f| %>
  <%= f.text_field :name %>
  <%= f.select :status, options_for_select([ "new", "in_process", "done" ], @task.status) %>
  <%= f.submit value: 'update task'%>
<% end %>

app/views/tasks/_task.html.erb
<tr id=<%= dom_id task %> class='row <%= task.status %>'>
  <td><p><%= task.name %></p></td>
  <td><p><%= task.status %></p></td>
  <td><%= link_to edit_project_task_path(task.project, task ), remote: true, :class => 'delete_task' do %>
        <i class="glyphicon glyphicon-pencil pencil"></i>
      <% end %>
  </td>
  <td><%= link_to [task.project, task], remote: true, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="glyphicon glyphicon-trash trash"></i>
      <% end %>
  </td>
</tr>

app/views/tasks/_update.html.erb
<td><p><%= @task.name %></p></td>
<td><p><%= @task.status %></p></td>
<td><%= link_to edit_project_task_path(@task.project, @task ), remote: true, :class => 'delete_task' do %>
      <i class="glyphicon glyphicon-pencil pencil"></i>
    <% end %>
</td>
<td><%= link_to [@task.project, @task], remote: true, method: :delete, data: { confirm: 'Are you sure?' } do %>
      <i class="glyphicon glyphicon-trash trash"></i>
    <% end %>
</td>

app/views/tasks/create.js.erb
if (!$("table").is("#tasks_project_<%= @project.id %>")){
  $('#project_<%= @project.id %>').append("<table id='tasks_project_<%= @project.id %>' class='table table-hover'>");
}
$("#new_task_project_<%= @project.id %>")
$("<%= escape_javascript(render @task) %>").fadeIn(300).appendTo("#tasks_project_<%= @project.id %>");
$("#new_task_project_<%= @project.id %> #task_name").val('');

app/views/tasks/destroy.js.erb
$("#task_<%= @task.id %>").remove();

app/views/tasks/edit.js.erb
$("#myModal .modal-title").text("Edit task: <%= @task.name %>");
$("#myModal .modal-body").html("<%= j (render 'edit') %>");
$('#myModal').modal("show");

app/views/tasks/update.js.erb
$("#task_<%= @task.id %>").removeClass('done');
$("#task_<%= @task.id %>").addClass("<%= @task.status%>");
$("#task_<%= @task.id %>").html("<%= j (render 'update') %>");
$('#myModal').modal("hide");